---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 20890.
--- DateTime: 2023/12/21 12:43
---
-- 比较线程标识与锁的标识是否一致
if(redis.call('get', KEYS[1]) == ARGV[1]) then
    -- 释放锁 del key
    return redis.call('del', KEYS[1])
end
return 0